var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/parent-report/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0aetm5~._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_12y2z2l.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y~gs73._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v73tbn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_parent-report_page_actions_10-93jx.js")
R.m(63543)
module.exports=R.m(63543).exports
