module.exports=[81925,a=>{"use strict";var b=a.i(87924),c=a.i(72131),d=a.i(50944),e=a.i(10849),f=a.i(63672);let g=[{id:"minecraft",label:"Minecraft",emoji:"⛏️",category:"游戏"},{id:"roblox",label:"Roblox",emoji:"🎮",category:"游戏"},{id:"mario",label:"马里奥",emoji:"🍄",category:"游戏"},{id:"pokemon",label:"宝可梦",emoji:"⚡",category:"游戏"},{id:"basketball",label:"篮球",emoji:"🏀",category:"运动"},{id:"soccer",label:"足球",emoji:"⚽",category:"运动"},{id:"skateboard",label:"滑板",emoji:"🛹",category:"运动"},{id:"swimming",label:"游泳",emoji:"🏊",category:"运动"},{id:"dinosaur",label:"恐龙",emoji:"🦕",category:"自然"},{id:"space",label:"太空",emoji:"🚀",category:"自然"},{id:"ocean",label:"海洋",emoji:"🌊",category:"自然"},{id:"animals",label:"动物",emoji:"🐾",category:"自然"},{id:"food",label:"美食",emoji:"🍜",category:"生活"},{id:"pets",label:"宠物",emoji:"🐱",category:"生活"},{id:"travel",label:"旅行",emoji:"✈️",category:"生活"},{id:"music",label:"音乐",emoji:"🎵",category:"生活"},{id:"springfestival",label:"春节",emoji:"🧧",category:"文化"},{id:"journeytowest",label:"西游记",emoji:"🐵",category:"文化"},{id:"kungfu",label:"功夫",emoji:"🥋",category:"文化"},{id:"anime",label:"动漫",emoji:"🎨",category:"文化"}];a.s(["default",0,function(){let a=(0,d.useRouter)(),[h,i]=(0,c.useState)([]),[j,k]=(0,c.useState)(!1);(0,c.useEffect)(()=>{(0,f.getClientAuth)()?k(!0):a.replace("/login")},[a]);let l=a=>{h.includes(a)?i(b=>b.filter(b=>b!==a)):h.length<3&&i(b=>[...b,a])},m=async()=>{if(3!==h.length)return;let b=(0,e.createClient)(),{data:{user:c}}=await b.auth.getUser();if(!c)return void a.push("/auth");await b.from("profiles").update({interests:h,onboarding_completed:!0}).eq("id",c.id);let d=(0,f.getClientAuth)(),g=(0,f.getClientProfile)()||(0,f.createDefaultProfile)(d);(0,f.setClientProfile)({...g,interests:h}),a.push("/daily")};return j?(0,b.jsx)("div",{className:"min-h-screen bg-gradient-to-br from-amber-50 to-orange-50 p-4 flex items-center justify-center",children:(0,b.jsx)("div",{className:"max-w-lg w-full animate-fade-in",children:(0,b.jsxs)("div",{className:"bg-white rounded-3xl shadow-lg shadow-amber-100 p-8",children:[(0,b.jsxs)("div",{className:"text-center mb-6",children:[(0,b.jsx)("div",{className:"text-5xl mb-3",children:"🎯"}),(0,b.jsx)("h1",{className:"text-2xl font-bold text-gray-800 mb-2",children:"你对什么感兴趣？"}),(0,b.jsx)("p",{className:"text-gray-500 text-sm",children:"选择3个你最感兴趣的话题，我会为你写相关的故事！"}),(0,b.jsxs)("div",{className:"text-amber-500 font-bold mt-2",children:["已选 ",h.length,"/3"]})]}),(0,b.jsxs)("div",{className:"mb-4",children:[(0,b.jsx)("h3",{className:"text-sm font-bold text-gray-400 mb-2 uppercase tracking-wider",children:"🎮 游戏"}),(0,b.jsx)("div",{className:"grid grid-cols-4 gap-2",children:g.filter(a=>"游戏"===a.category).map(a=>(0,b.jsxs)("button",{onClick:()=>l(a.id),className:`
                    p-3 rounded-2xl text-center transition-all duration-200
                    ${h.includes(a.id)?"bg-amber-400 text-white shadow-md scale-105 border-2 border-amber-500":"bg-amber-50 text-gray-700 hover:bg-amber-100 border-2 border-transparent"}
                    ${h.length>=3&&!h.includes(a.id)?"opacity-40":""}
                  `,children:[(0,b.jsx)("div",{className:"text-2xl mb-1",children:a.emoji}),(0,b.jsx)("div",{className:"text-[10px] font-medium leading-tight",children:a.label})]},a.id))})]}),(0,b.jsxs)("div",{className:"mb-4",children:[(0,b.jsx)("h3",{className:"text-sm font-bold text-gray-400 mb-2 uppercase tracking-wider",children:"⚽ 运动"}),(0,b.jsx)("div",{className:"grid grid-cols-4 gap-2",children:g.filter(a=>"运动"===a.category).map(a=>(0,b.jsxs)("button",{onClick:()=>l(a.id),className:`
                    p-3 rounded-2xl text-center transition-all duration-200
                    ${h.includes(a.id)?"bg-emerald-400 text-white shadow-md scale-105 border-2 border-emerald-500":"bg-emerald-50 text-gray-700 hover:bg-emerald-100 border-2 border-transparent"}
                    ${h.length>=3&&!h.includes(a.id)?"opacity-40":""}
                  `,children:[(0,b.jsx)("div",{className:"text-2xl mb-1",children:a.emoji}),(0,b.jsx)("div",{className:"text-[10px] font-medium leading-tight",children:a.label})]},a.id))})]}),(0,b.jsxs)("div",{className:"mb-4",children:[(0,b.jsx)("h3",{className:"text-sm font-bold text-gray-400 mb-2 uppercase tracking-wider",children:"🌿 自然"}),(0,b.jsx)("div",{className:"grid grid-cols-4 gap-2",children:g.filter(a=>"自然"===a.category).map(a=>(0,b.jsxs)("button",{onClick:()=>l(a.id),className:`
                    p-3 rounded-2xl text-center transition-all duration-200
                    ${h.includes(a.id)?"bg-sky-400 text-white shadow-md scale-105 border-2 border-sky-500":"bg-sky-50 text-gray-700 hover:bg-sky-100 border-2 border-transparent"}
                    ${h.length>=3&&!h.includes(a.id)?"opacity-40":""}
                  `,children:[(0,b.jsx)("div",{className:"text-2xl mb-1",children:a.emoji}),(0,b.jsx)("div",{className:"text-[10px] font-medium leading-tight",children:a.label})]},a.id))})]}),(0,b.jsxs)("div",{className:"mb-4",children:[(0,b.jsx)("h3",{className:"text-sm font-bold text-gray-400 mb-2 uppercase tracking-wider",children:"🏠 生活"}),(0,b.jsx)("div",{className:"grid grid-cols-4 gap-2",children:g.filter(a=>"生活"===a.category).map(a=>(0,b.jsxs)("button",{onClick:()=>l(a.id),className:`
                    p-3 rounded-2xl text-center transition-all duration-200
                    ${h.includes(a.id)?"bg-pink-400 text-white shadow-md scale-105 border-2 border-pink-500":"bg-pink-50 text-gray-700 hover:bg-pink-100 border-2 border-transparent"}
                    ${h.length>=3&&!h.includes(a.id)?"opacity-40":""}
                  `,children:[(0,b.jsx)("div",{className:"text-2xl mb-1",children:a.emoji}),(0,b.jsx)("div",{className:"text-[10px] font-medium leading-tight",children:a.label})]},a.id))})]}),(0,b.jsxs)("div",{className:"mb-6",children:[(0,b.jsx)("h3",{className:"text-sm font-bold text-gray-400 mb-2 uppercase tracking-wider",children:"🏮 文化"}),(0,b.jsx)("div",{className:"grid grid-cols-4 gap-2",children:g.filter(a=>"文化"===a.category).map(a=>(0,b.jsxs)("button",{onClick:()=>l(a.id),className:`
                    p-3 rounded-2xl text-center transition-all duration-200
                    ${h.includes(a.id)?"bg-violet-400 text-white shadow-md scale-105 border-2 border-violet-500":"bg-violet-50 text-gray-700 hover:bg-violet-100 border-2 border-transparent"}
                    ${h.length>=3&&!h.includes(a.id)?"opacity-40":""}
                  `,children:[(0,b.jsx)("div",{className:"text-2xl mb-1",children:a.emoji}),(0,b.jsx)("div",{className:"text-[10px] font-medium leading-tight",children:a.label})]},a.id))})]}),(0,b.jsx)("button",{onClick:m,disabled:3!==h.length,className:`
              w-full py-4 rounded-2xl font-bold text-lg transition-all
              ${3===h.length?"bg-gradient-to-r from-amber-400 to-orange-400 text-white shadow-md hover:shadow-lg active:scale-[0.98]":"bg-gray-200 text-gray-400 cursor-not-allowed"}
            `,children:3===h.length?"开始读故事吧！📖":`再选 ${3-h.length} 个`})]})})}):null}])}];

//# sourceMappingURL=src_app_interests_page_tsx_0eoy1h3._.js.map