var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/daily/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__12ci9vj._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_03hs8ba.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y~gs73._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v73tbn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_daily_page_actions_0_k5.wa.js")
R.m(15450)
module.exports=R.m(15450).exports
